#!/usr/bin/env bash
# Export the web client and/or the dedicated server into ../build/.
# Usage: game/scripts/export.sh [web|server|all]   (needs Godot export templates)
set -euo pipefail
cd "$(dirname "$0")/.."
GODOT="${GODOT:-godot}"
target="${1:-all}"
# CI sets BUILD_VERSION to the commit SHA. Clients and servers only play together when
# their versions match (see core/net/network.gd); without it the build reports "dev".
if [[ -n "${BUILD_VERSION:-}" ]]; then
  [[ "$BUILD_VERSION" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "bad BUILD_VERSION" >&2; exit 1; }
  printf '# Generated by scripts/export.sh; not committed.\nextends RefCounted\n\nconst VERSION := "%s"\n' \
    "$BUILD_VERSION" > build_info.gd
  trap 'rm -f build_info.gd build_info.gd.uid' EXIT
  echo "Build version: $BUILD_VERSION"
fi
"$GODOT" --headless --import >/dev/null 2>&1 || true
if [[ "$target" == web || "$target" == all ]]; then
  mkdir -p ../build/web
  "$GODOT" --headless --export-release "Web" ../build/web/index.html
fi
if [[ "$target" == server || "$target" == all ]]; then
  mkdir -p ../build/server
  "$GODOT" --headless --export-release "Linux Server" ../build/server/the-game-server.x86_64
fi
